default_roles:
  # - aerospace
  # - brew
  - all
  - shell
  # - fish
  # - neovim
  # - obsidian
  # - system
  # - taskfile
  # - tmux
  # - zed
  # - zsh

disabled_roles:
  - utils
  - ghostty
  - thunderbird
