default_roles:
  - git
  - neovim
  - tmux
  - zsh

disabled_roles:
  - system
  - fish
  - bash
  - docker
  - go
  - opentofu
  - utils
  - k8s
  - amfora

git_user_name: "jchancey"
git_user_email: "jchancey@oneinc.com"

