


#corualiases
alias c=code
alias dotd='~/.dotfiles/dotdrop.sh'

# ros vars and aliases
# source /opt/ros/melodic/setup.bash
# source devel/setup.bash
alias ds='source devel/setup.bash'
export devel=devel/setup.bash
alias ghusky='roslaunch husky_gazebo husky_playpen.launch'

# general use
# alias sai='sudo apt install'
alias waldir='cd $HOME/Pictures/wallpapers'
alias wals='wal -i $HOME/Pictures/wallpapers'
alias rbrc='source ~/.bashrc'
alias ei3='vim ~/.i3/config'
alias eb='vim ~/.bashrc'
alias rxr='xrdb ~/.Xresources'
alias s='source'
alias r='ranger'
alias p='sudo pacman'



