---
- name: "Fish | Link"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/fish"
    state: link
    force: true

- name: Run openSUSE Tasks
  ansible.builtin.import_tasks: suse.yml
  when: ansible_os_family == 'Suse'
  become: true

- name: Get location of fish shell
  command: which fish
  register: fish_location_cmd
  ignore_errors: true
  changed_when: false

- name: Set fish location as fact
  set_fact:
    fish_location: "{{ fish_location_cmd.stdout }}"
  when: fish_location_cmd.rc == 0

