---
- name: "Fish | Install"
  community.general.zypper:
    name:
      - fish
    state: latest
  become: true

- name: "Fish | Set default terminal"
  user:
    name: "{{ host_user }}"
    shell: /usr/bin/fish
  become: true

