---
- name: Run openSUSE Tasks
  ansible.builtin.import_tasks: suse.yml
  when: ansible_os_family == 'Suse'
  become: true

- name: "Bash | Copy .aliases"
  ansible.builtin.copy:
    src: ".aliases"
    dest: "{{ ansible_user_dir }}/.aliases"
    mode: "0644"

- name: "Bash | Copy .env"
  ansible.builtin.copy:
    src: ".env"
    dest: "{{ ansible_user_dir }}/.env"
    mode: "0644"

- name: "Bash | Copy .env_wayland"
  ansible.builtin.copy:
    src: ".env_wayland"
    dest: "{{ ansible_user_dir }}/.env_wayland"
    mode: "0644"

- name: "Bash | Copy .bashrc"
  ansible.builtin.copy:
    src: ".bashrc"
    dest: "{{ ansible_user_dir }}/.bashrc"
    mode: "0644"
