#!/bin/sh
# perform minimal preparation and run ansible
export DOTFILES_USER=$USER
echo "$USER ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/$DOTFILES_USER > /dev/null
ansible-playbook $(git rev-parse --show-toplevel)/main.yml
