config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_i3:
    dst: ~/.i3
    src: i3
  d_scripts:
    dst: ~/.scripts
    src: scripts
  f_bash_aliases:
    dst: ~/.bash_aliases
    src: bash_aliases
  f_bash_profile:
    dst: ~/.bash_profile
    src: bash_profile
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_compton.conf:
    dst: ~/.config/compton.conf
    src: config/compton.conf
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_i3-scrot.conf:
    dst: ~/.config/i3-scrot.conf
    src: config/i3-scrot.conf
  f_profile:
    dst: ~/.profile
    src: profile
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  f_config.base:
    src: i3/config.base
    dst: ~/.i3/config.base
  f_config.ducky-107:
    src: i3/config.ducky-107
    dst: ~/.i3/config.ducky-107
  d_cat:
    src: cat
    dst: ~/.dotfiles/cat
profiles:
  Miya:
    dotfiles:
    - f_bashrc
    - f_bash_aliases
    - f_bash_profile
    - f_tmux.conf
    - d_scripts
    - f_gitconfig
  pholipid:
    dotfiles:
    - f_xinitrc
    - f_i3-scrot.conf
    - f_compton.conf
    - f_xresources
    - f_profile
    - f_bashrc
    - f_bash_aliases
    - f_bash_profile
    - d_i3
    - f_tmux.conf
    - d_scripts
    - f_gitconfig
    - f_zshrc
  ducky-107.localdomain:
    dotfiles:
    - f_bashrc
    - f_bash_aliases
    - f_bash_profile
    - f_tmux.conf
    - d_scripts
    - f_compton.conf
    - f_xresources
    - d_i3
    - f_i3-scrot.conf
    - f_xinitrc
    - f_config.base
    - f_config.ducky-107
    - d_cat
  ball:
    dotfiles:
    - f_bashrc
    - f_bash_aliases
    - f_bash_profile
    - f_tmux.conf
    - d_scripts
    - f_compton.conf
    - f_xresources
    - d_i3
    - f_i3-scrot.conf
    - f_xinitrc
    - f_config.base
    - f_config.ducky-107
    - d_cat