---
services:
  webtop:
    image: void-raft-kasm
    container_name: void-raft-kasm
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/Los_Angeles
      - SUBFOLDER=/ #optional
      - TITLE=void-raft-kasm #optional
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "2gb" #optional
    restart: unless-stopped
