#!/bin/sh

if [ -x "$(command -v brew)" ]; then
  packages_path="$HOME/.local/state/values/packages"
  brew_packages="$(brew list --formulae | wc -l)"
  cask_packages="$(brew list --cask 2>/dev/null | wc -l)"
  packages="$((brew_packages + cask_packages))"
  echo $packages >"$packages_path"
  echo updated $packages \> "$packages_path"
fi
