#!/bin/sh

if [ -x "$(command -v brew)" ]; then
	brew_packages="$(brew list --formulae | wc -l)"
	cask_packages="$(brew list --cask 2> /dev/null | wc -l)"
	packages="$(( ${brew_packages} + ${cask_packages} ))"
	echo $packages > $HOME/.local/state/values/packages
fi

