#!/bin/sh
#
# ufetch-macos - tiny system info for macos

## INFO

# user is already defined
host="$(hostname -s)"
os="$(sw_vers -productName) $(sw_vers -productVersion)"
kernel="$(uname -sr)"
uptime="$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}' | sed -e 's/^[ \t]*//')"
shell="$(basename "${SHELL}")"

## PACKAGE MANAGER DETECTION

echo BREW_NUMBER_INSTALLED_PACKAGES
packages="NUM_BREW_PACKAGES$(echo "${packages}" | sed -e 's/^[ /t]*//')"

## UI DETECTION

if [ -n "${DE}" ]; then
	ui="${DE}"
	uitype='DE'
elif [ -n "${WM}" ]; then
	ui="${WM}"
	uitype='WM'
else
	ui='Aqua'
	uitype='UI'
fi

ui="$(basename "${ui}")"
0
## DEFINE COLORS

# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold 2> /dev/null)"
	black="$(tput setaf 0 2> /dev/null)"
	red="$(tput setaf 1 2> /dev/null)"
	green="$(tput setaf 2 2> /dev/null)"
	yellow="$(tput setaf 3 2> /dev/null)"
	blue="$(tput setaf 4 2> /dev/null)"
	magenta="$(tput setaf 5 2> /dev/null)"
	cyan="$(tput setaf 6 2> /dev/null)"
	white="$(tput setaf 7 2> /dev/null)"
	reset="$(tput sgr0 2> /dev/null)"
fi

# you can change these
lc="${reset}${bold}"                # labels
nc="${reset}${bold}"                # user and hostname
ic="${reset}"                       # info
c0="${reset}"                       # first color

## OUTPUT

cat <<EOF
${c0}          _${reset}
${c0}         (/     ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}    .---__--.   ${lc}OS:        ${ic}${os}${reset}
${c0}   /         \  ${lc}KERNEL:    ${ic}${kernel}${reset}
${c0}  |         /   ${lc}UPTIME:    ${ic}${uptime}${reset}
${c0}  |         \\_  ${lc}PACKAGES:  ${ic}${packages}${reset}
${c0}   \         /  ${lc}SHELL:     ${ic}${shell}${reset}
${c0}    \`._.-._.\`   ${lc}${uitype}:        ${ic}${ui}${reset}

EOF

