#!/bin/sh
# ufetch-macos - tiny system info for macos

## INFO

# user is already defined
host="$(hostname -s)"
os="$(sw_vers -productName) $(sw_vers -productVersion)"
kernel="$(uname -sr)"
uptime="$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}' | sed -e 's/^[ \t]*//')"
shell="$(basename "${SHELL}")"
packages=$(<$HOME/.local/state/values/packages)

## UI DETECTION

if [ -n "${DE}" ]; then
	ui="${DE}"
	uitype='DE'
elif [ -n "${WM}" ]; then
	ui="${WM}"
	uitype='WM'
else
	ui='Aqua'
	uitype='UI'
fi

ui="$(basename "${ui}")"

bold='[1m'
black='[30m'
red='[31m'
green='[32m'
yellow='[33m'
blue='[34m'
magenta='[35m'
cyan='[36m'
white='[37m'
grey='[90m'
reset='[0m'

# you can change these
lc="${reset}${bold}"                # labels
nc="${reset}${bold}"                # user and hostname
ic="${reset}"                       # info
c0="${reset}"                       # first color

## OUTPUT

cat <<EOF
${c0}          _${reset}
${c0}         (/     ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}    .---__--.   ${lc}OS:        ${ic}${os}${reset}
${c0}   /         \  ${lc}KERNEL:    ${ic}${kernel}${reset}
${c0}  |         /   ${lc}UPTIME:    ${ic}${uptime}${reset}
${c0}  |         \\_  ${lc}PACKAGES:  ${ic}${packages}${reset}
${c0}   \         /  ${lc}SHELL:     ${ic}${shell}${reset}
${c0}    \`._.-._.\` ${lc}${ci}  ${red}███${green}███${yellow}███${blue}███${magenta}███${cyan}███${reset}

EOF

