---
- name: "Utils | Install misc utilities"
  become: yes
  community.general.zypper:
    name:
      - lsd
      - bottom
      - lazygit
      - tree-sitter
      - fzf
      - busybox-net-tools
      - bind-utils
      - hostname
      - inxi
    state: latest
