---
- name: "Utils | Install misc utilities"
  become: true
  community.general.zypper:
    name:
      - lsd
      - bottom
      - lazygit
      - tree-sitter
      - fzf
      - net-tools-deprecated
      - bind-utils
      - hostname
      - inxi
      - lsb-release
    state: latest
