---
- name: Wezterm | Ensure directory exists
  file:
    path: "{{ ansible_user_dir }}/.config/wezterm/"
    state: directory
    mode: "0755"

- name: "Wezterm | Configure"
  ansible.builtin.file:
    src: "{{ role_path }}/files/wezterm"
    dest: "{{ ansible_user_dir }}/.config/wezterm"
    state: link
    force: true
