---
- name: "Tmux | Install"
  become: true
  community.general.zypper:
    name:
      - tmux
      - fzf
      - fzf-tmux
      - bat
    state: latest

- name: Tmux | Ensure directory exists
  become: true
  file:
    path: "/run/tmux/1000"
    state: directory
    owner: ansible-user
    group: ansible-user
    mode: '0700'
